<%@ Page Title="" Language="C#" MasterPageFile="~/admin/Admin.Master" AutoEventWireup="true" CodeBehind="Expenses.aspx.cs" Inherits="Fitness_Hub.admin.Expenses" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="page-wrapper">
        <div class="page-breadcrumb">
            <div class="row">
                <div class="col-12 d-flex no-block align-items-center">
                    <h4 class="page-title">Form Basic</h4>
                    <div class="ml-auto text-right">
                        <nav aria-label="breadcrumb">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="#">Home</a></li>
                                <li class="breadcrumb-item active" aria-current="page">Add Trainer</li>
                            </ol>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">

                    <div class="form-horizontal">
                        <div class="card-body">
                            <h4 class="card-title">Add Informations</h4>
                            <div class="form-group row">
                                <label for="fname" class="col-sm-3 text-right control-label col-form-label">Expenses Name</label>
                                <div class="col-sm-9">
                                    <asp:Label ID="lblid" runat="server" Text=""></asp:Label>
                                    <asp:TextBox runat="server" ID="txtname" class="form-control" placeholder="Expenses Name Here"></asp:TextBox>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="lname" class="col-sm-3 text-right control-label col-form-label">Amount</label>
                                <div class="col-sm-9">
                                    <asp:TextBox runat="server" ID="txtamt" class="form-control" placeholder="Amount Here"></asp:TextBox>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="lname" class="col-sm-3 text-right control-label col-form-label">Descp</label>
                                <div class="col-sm-9">
                                    <asp:TextBox runat="server" ID="txtdesc" class="form-control" placeholder="Descc ere"></asp:TextBox>
                                </div>
                            </div>
                            <div class="border-top">
                                <div class="card-body">
                                    <asp:Button ID="Button1" runat="server" Text="Save" OnClick="Button1_Click" CssClass="btn btn-primary" />
                                </div>
                            </div>
                            <div class="border-top" style="margin-left: 80%; position: absolute; margin-top: -7%;">
                                <div class="card-body">
                                    <asp:Button ID="Button2" runat="server" Text="Refresh" OnClick="Button2_Click" CssClass="btn btn-primary" />
                                </div>
                            </div>
                            <asp:Label runat="server" ID="lbl"></asp:Label>
                            <br />
                            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="ExpenseId" DataSourceID="SqlDataSource1" Width="100%" AllowPaging="True" AllowSorting="True" CellPadding="4" ForeColor="#333333" GridLines="None">
                                <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                                <Columns>
                                    <asp:BoundField DataField="ExpenseName" HeaderText="Name" SortExpression="ExpenseName"  ItemStyle-Width="150" ItemStyle-CssClass="text-center" HeaderStyle-CssClass="text-center"/>
                                    <asp:BoundField DataField="ExpensePrice" HeaderText="Expense Price" SortExpression="ExpensePrice" ItemStyle-Width="150" ItemStyle-CssClass="text-center" HeaderStyle-CssClass="text-center"/>
                                    <asp:BoundField DataField="ExpenseDetail" HeaderText="Expense Description" SortExpression="ExpenseDetail" HeaderStyle-CssClass="text-center" ItemStyle-CssClass="text-center"/>
                                </Columns>
                                <EditRowStyle BackColor="#999999" />
                                <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                                <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                                <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                                <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                                <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                                <SortedAscendingCellStyle BackColor="#E9E7E2" />
                                <SortedAscendingHeaderStyle BackColor="#506C8C" />
                                <SortedDescendingCellStyle BackColor="#FFFDF8" />
                                <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
                            </asp:GridView>
                            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:GymCon %>" SelectCommand="SELECT * FROM [DailyExpense]" DeleteCommand="DELETE FROM [DailyExpense] WHERE [ExpenseId] = @ExpenseId" InsertCommand="INSERT INTO [DailyExpense] ([ExpenseName], [ExpensePrice], [ExpenseDetail]) VALUES (@ExpenseName, @ExpensePrice, @ExpenseDetail)" UpdateCommand="UPDATE [DailyExpense] SET [ExpenseName] = @ExpenseName, [ExpensePrice] = @ExpensePrice, [ExpenseDetail] = @ExpenseDetail WHERE [ExpenseId] = @ExpenseId">
                                <DeleteParameters>
                                    <asp:Parameter Name="ExpenseId" Type="Int32" />
                                </DeleteParameters>
                                <InsertParameters>
                                    <asp:Parameter Name="ExpenseName" Type="String" />
                                    <asp:Parameter Name="ExpensePrice" Type="Decimal" />
                                    <asp:Parameter Name="ExpenseDetail" Type="String" />
                                </InsertParameters>
                                <UpdateParameters>
                                    <asp:Parameter Name="ExpenseName" Type="String" />
                                    <asp:Parameter Name="ExpensePrice" Type="Decimal" />
                                    <asp:Parameter Name="ExpenseDetail" Type="String" />
                                    <asp:Parameter Name="ExpenseId" Type="Int32" />
                                </UpdateParameters>
                            </asp:SqlDataSource>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="scripts" runat="server">
</asp:Content>
